### ISSUE TITLE
Providing a data dump?

### ISSUE THREAD

**Issue by jpetitcolas** [leblanc-simon/presta-faker#1]
First, thanks for this project. It really helps when you just need a Prestashop demo. :)

Populating database using Prestashop web-service is pretty slow. Wouldn't it be a good idea to provide some SQL dumps of generated data? I'm not sure which tables should be exported (that's my first Prestashop contact), but it may worth it.

**Comment by leblanc-simon** [comment]
Yes, it's a good idea. I do a first version (tested with Prestashop 1.5.6) without the pictures support. It's available in the branch features/sql

I will test with last version of Prestashop and add pictures support before to merge into master.

**Comment by leblanc-simon** [comment]
Tested with last version of Prestashop, it seems OK. Merged into the master
